### ISSUE TITLE
ProjectedCRS units

### ISSUE THREAD

**Issue by jmirtsch** [Autodesk/revit-ifc#290]
Hi,

This looks amiss to me, a conversion based unit for "METER" with a scale factor looking like feet.
METER should be mapped to SIUnit Metre.

#124= IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
#125= IFCMEASUREWITHUNIT(IFCRATIOMEASURE(0.3048),#124);
#126= IFCCONVERSIONBASEDUNIT(#123,.LENGTHUNIT.,'METER',#125);
#127= IFCPROJECTEDCRS('EPSG:28355','Map Grid of Australia Zone 55, using GDA94 datum','GDA94',$,$,$,#126);
#129= IFCMAPCONVERSION(#114,#127,319000,5814000,26.0499999999984,1.,6.50052386051703E-15,$);

Thanks,

Jon

**Comment by jmirtsch** [comment]
I'm adding some more description to this issue.  If it's not clear, please let me know.

I really like the nomination of the EPSG code to facilitate map conversion in IFC.  However, the implementation seems to have some short comings.  As mentioned above, the map conversion nominates a unit in Metres, however it nomninates a conversion based unit with an incorrect scale factor.  It could simply use an SI unit.  It also fails to scale the eastings, northings and height, which are nominated in project units (should be 1000 times smaller to match nominated units).

![210422 export georeferenced](https://user-images.githubusercontent.com/791757/115717618-b1ad4080-a3bd-11eb-8b40-4316e0d00d7f.png)


Here's a revit 2020 file if you want a test model.
[210420 georeferenced flinders street.zip](https://github.com/Autodesk/revit-ifc/files/6358335/210420.georeferenced.flinders.street.zip)

Thanks,

Jon


Thanks,

Jon

**Comment by WawanSolihin** [comment]
This issue has been fixed in the current development branch. The reason is actually very simple. The code checks for units and perform conversion as needed. However, I found that IFC uses METRE, while EPSG uses METER and therefore the comparison fails. I will bring this changes to 2020 and 2021 since it is actually very simple change.

**Comment by Moult** [comment]
Unfortunately the latest install from https://apps.autodesk.com/RVT/en/Detail/Index?id=7265544480016320144&appLang=en&os=Win64 still is outdated and does not have this fix so it is still broken for users.

**Comment by WawanSolihin** [comment]
The last update for Revit 2021 is release 21.4.2.0. We focus on Revit 2023 and Revit 2022 updates from now on due to high level of incompatible changes from the latest to the older versions.
But I brought some fixes, mainly related to the mapunit in IfcProjectedCRS. I have posted the draft release for 21.4.3.0 here https://github.com/Autodesk/revit-ifc/releases/tag/IFC_v21.4.3.0 . This change works in 2022 and later and should work in 2021 (I did simple test). Please check whether this works. It is currently unsigned, if you don't mind.

**Comment by Moult** [comment]
I can confirm that this is fixed in 2021 and above. Hooray!

**Comment by WawanSolihin** [comment]
Great!
