### ISSUE TITLE
Please fix IfcClassification

### ISSUE THREAD

**Issue by louistrue** [Autodesk/revit-ifc#546]
I cant get Classification to work anymore, no matter what Version of the exporter I install. Both for Revit 2022 and 2023. There is either no classification exported, for example when I leave the "Classification Code" empty (even though that is supposed to be the default value I have to put in "Classification Code") or the classification gets split up in many parts:

![image](https://user-images.githubusercontent.com/78563314/201956633-21f16c86-9d3d-440d-8fb1-105f6e6eb943.png)

![image](https://user-images.githubusercontent.com/78563314/201956591-2fba25f8-a71c-4530-8d1e-0cbb057d912c.png)

**Comment by AngelVelezSosa** [comment]
@WawanSolihin - as far as I know there are no regressions here.

**Comment by WawanSolihin** [comment]
Not that I know of, but there is also another bug report that is similar. I will take a look as soon as I am available.

**Comment by louistrue** [comment]
Thanks, see also:

https://github.com/Autodesk/revit-ifc/issues/543#issue-1442680790
https://github.com/Autodesk/revit-ifc/issues/509#issue-1364453343
https://github.com/Autodesk/revit-ifc/issues/489#issue-1316069648

**Comment by louistrue** [comment]
![image](https://user-images.githubusercontent.com/78563314/202571105-b93c1352-c1f9-4342-aea2-29c3b4de323b.png)

Thats whats going wrong...

**Comment by louistrue** [comment]
Seems like the newest Solibri update fixed this on the Solibri side: https://github.com/Autodesk/revit-ifc/issues/543#issuecomment-1319568854

Still think this should be fixed in the exporter as well...

**Comment by HenkMolhoek** [comment]
The latest version of Solibri has changed the Uniformat Classification to Uniformat.
This has already been reported to Solibri.
But this does not solve the problem in IFC

**Comment by dvrvb** [comment]
Hopefully that was reported as a congratulation to Solibri for that correction and not as bug.

**Comment by AngelVelezSosa** [comment]
This seems like the same issue as #543 but also I am not sure I see a bug on the exporter side.  The name in IfcRelAssociatesClassification should not be relevant to a viewer.  I will reopen if someone shows me that I am missing something here.

**Comment by louistrue** [comment]
I disagree,  @AngelVelezSosa . It is just confusing to have that value there and I think many agree. Just because Solibri fixed an old bug that was probably discovered after the recent changes in the Revit exporter doesn't mean it's fine. Other viewers/applications have similar trouble. 

Since "Name" is an optional attribute: why not just leave it empty?

**Comment by AngelVelezSosa** [comment]
I will check to see if the name has value, and if it doesn't really we can leave it empty.  But I am not sure why that value would be confusing or not.  This isn't the name of the classification; this is the name of a reference entity that is an implementation detail for how IFC is represented (by making relationships be first-class entities instead of being attributes).  It seems odd that an application looks at a value and, if it is set, does the wrong thing with it.

**Comment by WillemdBr** [comment]
@AngelVelezSosa @louistrue @dvrvb @HenkMolhoek 
We've contacted Solibri about this issue and they've send us their answer:

Hi Willem,

From the link below, you can see the classification name should be taken from IFCCLASSIFICATION

https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcexternalreferenceresource/lexical/ifcclassification.htm

Earlier versions of Solibri derived the classification name from the relation IFCRELASSOCIATESCLASSIFICATION

https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifckernel/lexical/ifcrelassociatesclassification.htm

I hope this is clear, it is not a bug in Solibri but a fix for the updated IFC standards.

Thank you.

Best regards,
Solibri Support Team

**Comment by HenkMolhoek** [comment]
Hello,


When we load the IFC into Navisworks, we see the following.
Because of this we have to rewrite all search sets. Or will I also be adjusted in navisworks?


***@***.***



It does work on BIM360 and in model coordination

***@***.***







Van: Willem_dB ***@***.***>
Verzonden: maandag 21 november 2022 16:10
Aan: Autodesk/revit-ifc ***@***.***>
CC: Molhoek, Henk ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Autodesk/revit-ifc] Please fix IfcClassification (Issue #546)

CAUTION this email originated from outside of BAM so be careful when opening attachments or links. To report as spam, please use the report message button in Outlook.
________________________________

@AngelVelezSosa<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAngelVelezSosa&data=05%7C01%7Chenk.molhoek%40bam.com%7Cb0412d6ffc934e2c37b508dacbd26e2d%7Cbf5f4046a1dc4119aa8abfb9fbf46271%7C0%7C0%7C638046401901574638%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p5NGzG8ibqrpbfk06lTtJK4GoUfDii3b3zp7z1eABf4%3D&reserved=0> @louistrue<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flouistrue&data=05%7C01%7Chenk.molhoek%40bam.com%7Cb0412d6ffc934e2c37b508dacbd26e2d%7Cbf5f4046a1dc4119aa8abfb9fbf46271%7C0%7C0%7C638046401901574638%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IGj%2FEn0liLqvKmk1KDcU%2F5UD%2FVU7lB6Ei6q%2BxEDg5nA%3D&reserved=0> @dvrvb<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdvrvb&data=05%7C01%7Chenk.molhoek%40bam.com%7Cb0412d6ffc934e2c37b508dacbd26e2d%7Cbf5f4046a1dc4119aa8abfb9fbf46271%7C0%7C0%7C638046401901574638%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UL57HjbWqNxsRCskNjRTslfD6As5Hz2Shv%2BqUsZYZOM%3D&reserved=0> @HenkMolhoek<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHenkMolhoek&data=05%7C01%7Chenk.molhoek%40bam.com%7Cb0412d6ffc934e2c37b508dacbd26e2d%7Cbf5f4046a1dc4119aa8abfb9fbf46271%7C0%7C0%7C638046401901730851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=958JIMNNCiJ5lKtZIZYyjsyNE2YlmknoGN5U%2FD2vUyY%3D&reserved=0>
We've contacted Solibri about this issue and they've send us their answer:

Hi Willem,

From the link below, you can see the classification name should be taken from IFCCLASSIFICATION

https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcexternalreferenceresource/lexical/ifcclassification.htm<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstandards.buildingsmart.org%2FIFC%2FRELEASE%2FIFC2x3%2FTC1%2FHTML%2Fifcexternalreferenceresource%2Flexical%2Fifcclassification.htm&data=05%7C01%7Chenk.molhoek%40bam.com%7Cb0412d6ffc934e2c37b508dacbd26e2d%7Cbf5f4046a1dc4119aa8abfb9fbf46271%7C0%7C0%7C638046401901730851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=i2lAwuk4wLpUT0Ywd5ExQLgV7HU4L4Sj%2B8DpHeEYmRE%3D&reserved=0>

Earlier versions of Solibri derived the classification name from the relation IFCRELASSOCIATESCLASSIFICATION

https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifckernel/lexical/ifcrelassociatesclassification.htm<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstandards.buildingsmart.org%2FIFC%2FRELEASE%2FIFC2x3%2FTC1%2FHTML%2Fifckernel%2Flexical%2Fifcrelassociatesclassification.htm&data=05%7C01%7Chenk.molhoek%40bam.com%7Cb0412d6ffc934e2c37b508dacbd26e2d%7Cbf5f4046a1dc4119aa8abfb9fbf46271%7C0%7C0%7C638046401901730851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZxkakxKoZUsEOvpsl6RpzjKOdDnJIstdvGoTKH86xZM%3D&reserved=0>

I hope this is clear, it is not a bug in Solibri but a fix for the updated IFC standards.

Thank you.

Best regards,
Solibri Support Team

-

**Comment by AngelVelezSosa** [comment]
@WillemdBr : Doesn't what Solibri state seem like there is a Solibri bug?  It should take the value from IfcClassification, not IfcRelAssociatesClassification?

Regardless, we will look into making a fix for compatibility, but it does seem like a bunch of viewers decided to do something odd.

**Comment by WawanSolihin** [comment]
> @AngelVelezSosa @louistrue @dvrvb @HenkMolhoek We've contacted Solibri about this issue and they've send us their answer:
> 
> Hi Willem,
> 
> From the link below, you can see the classification name should be taken from IFCCLASSIFICATION
> 
> https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcexternalreferenceresource/lexical/ifcclassification.htm
> 
> Earlier versions of Solibri derived the classification name from the relation IFCRELASSOCIATESCLASSIFICATION
> 
> https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifckernel/lexical/ifcrelassociatesclassification.htm
> 
> I hope this is clear, it is not a bug in Solibri but a fix for the updated IFC standards.
> 
> Thank you.
> 
> Best regards, Solibri Support Team

I am not sure what Solibri support team referred to that says the Classification name is taken from ifcrelassociatesclassification in the specification. The schema specifies that the classification name may be specified by IfcClassification, which may be optional (not specified). The name in ifcrelassociatesclassification, as name in the other entities is simply an identification of the entity itself (in this case ifcrelassociatesclassification) and should not be the reference to the Classification itself.
Regardless, I think it is an issue with Solibri

**Comment by dvrvb** [comment]
Since when the IFC2x3 TC1 can be considered as "updated" IFC standard??? (as far as I know buildingSMART did not do any sneaky updates last month in the official TC1 specification)

**Comment by Moult** [comment]
Apologies I'm writing this on a phone on holiday but from what I can tell the name and description on the rel associates classification should not have any impact on the semantics of classification names or reference names.

So yes, Revit is doing things correctly and it is Solibri which needs to fix things (which from what I read in this thread is already fixed?)

**Comment by HenkMolhoek** [comment]
Thank you for explaining and clarifying the change.
Will there also be a change to Navisworks because this viewer does not read the IFC properly.
Here too we are the same result as what Solibri 9.12 showed.

**Comment by AngelVelezSosa** [comment]
I'll check to see why Navis has an issue here.

**Comment by HenkMolhoek** [comment]
The problem arises when Conversion Method Legacy (v1) is activated. We use this method.
Conversion Method V2 and V3 are going well.
![Knipsel](https://user-images.githubusercontent.com/45469583/203508642-e5acc975-c07b-4ea1-8986-1100d7fd5f0c.PNG)

**Comment by AngelVelezSosa** [comment]
Then it seems as if it has already been resolved in Navis and isn't a problem in BIM360.

**Comment by HenkMolhoek** [comment]
It is fixed in BIM360 and in navisworks but not in Navisworks Conversion Method Legacy (v1) .
V1 is the fastest and most reliable method to convert IFC. we are using Navisworks Manage 2022 Update 3
or Navisworks Manage 2023 Update 1

can you look at this?
![2022-11-23_13-54-50](https://user-images.githubusercontent.com/45469583/203552110-4f6b1620-63d5-4815-8425-518ca5713d1f.png)

**Comment by HenkMolhoek** [comment]
is there an update yet?
