### ISSUE TITLE
Problem: Bug Revit 2022 IFC Export Shaft opening in floors

### ISSUE THREAD

**Issue by MikeRCAD** [Autodesk/revit-ifc#609]
Hello,

The Revit 2022 IFC exporter 22.6.0.0 (and 22.6.2.0) has a issue with Shaft openings that share a edge with floor(s).

Bug occurs when there is also a shaft within the floor, if there are only shafts sharing egdes with the floor, the floor boundary is exported correctly. 

After some testing I found out the combination of steps to reproduce this:
1. draw a rectangular floor of level1
2. copy floor to level 2
3. draw a shaft intersecting both floors AND have the shaft share a edge with the floors
4. draw a shaft in the middle of the floor and only let it intersect one of the floors.
5. export to IFC (2x3 scheme)

The floor boundary with the 2 schaft openings isn't correct, the other one is.

Further issue (minor) the shaft sharing it's boundary isn't exported as opening in the Ifc.

Below a image with the IFC export on the left (with missing opening) and revit file on the right (with shafts selected)
![Revit2022_ifc_shaft_issue](https://user-images.githubusercontent.com/117643427/223349442-7a903854-ec87-447e-acbe-06b30fc48a39.png)

**Comment by LSMMrdk** [comment]
I believe this still applies to the 22.7.0 and also newer versions of Revit and the IFC exporter such as 24.2.0.49.
At least shaft openings still appear to be missing from exports.

**Comment by T-Silkjaer** [comment]
This issue is still a problem in Revit 2024

**Comment by fullagubben** [comment]
I recently also discovered this problem in v.24.2.20.0.

**Comment by Bert-je** [comment]
Is anyone addressing this? it still persists to be an issue in latest IFC export versions, and only very old versions do export properly. 
I am working with Revit 2022, 2023, 2024. When I tested with a test project, 2024 seamed to work okay with Autodesk Revit stock IFC Exporter, but now when I actualy work with it on projects, it still goes wrong, having to downgrade IFC Exporter,possisbly starting other allready solved problems to be an issue with my projects.
In some cases using IFC4 instead of IFC2x3 solves the problem, but not all our custimers can, do accept IFC4. 

In my experiece, it is not just sharing an edge, but also crossing an edge thah causes this problem.

In one occasion i had a similar experience with exporting from Revit 2022.  A window/door sharing an edge with a wall-end led to an export with the remaining lintel over the door in the concrete wall not exported, even with the downgraded version o IFC Exporter.  

I use 23.2.5.0 and 22.5.1. and now looking for an IFC exporter for Revit 24 from around / before those updates, to see if that will solve the problem with Revit 2024

**Comment by LSMMrdk** [comment]
I believe this is resolved if you use a newer version for Revit 2024 and 2025. At least, I have been unable to recreate it with my simple test project, which caught the error earlier. Believe it was using 24.3.20

**Comment by ArtemHnatko** [comment]
I have verified this issue and found that it **still reproduces with add-on version 23.3** but **does not reproduce on version 23.4.1**.

Additionally, the issue **does not reproduce** on the following versions:
- Autodesk Revit 2024 (IFC 24.3.20.0)
- Autodesk Revit 2025 (IFC 25.4.0.27)

During testing, I observed that the **shaft opening cutting through both floors is not exported as an opening**, while the **shaft opening affecting only one floor is correctly exported as an opening**.

![Image](https://github.com/user-attachments/assets/331d57ec-3aa5-49c5-aa88-ec225611d7a4)

**Comment by ArtemHnatko** [comment]
@Bert-je 
I attempted to reproduce the issue following your described setup, including testing with different IFC exporter versions and floor configurations, but I was unable to reproduce the problem.

If you have a specific test case or additional details that could help isolate the issue, please share them, and I'll be happy to investigate further.

![Image](https://github.com/user-attachments/assets/7735f92a-10eb-4e2d-9e58-252b5a208202)

[Export_Shaft_opening_in_floors_with_Layers_R24.zip](https://github.com/user-attachments/files/19566771/Export_Shaft_opening_in_floors_with_Layers_R24.zip)
