### ISSUE TITLE
PR: IfcExport Update 22.6.2.0, IfcEnergyConversionDevice datatype power gives invalid values

### ISSUE THREAD

**Issue by EPKoele** [Autodesk/revit-ifc#641]
### Problem Description

Revit parameter "Power" exported to IFC 2x3 results in an invalid value in IFC when using Power datatype. With dataype Real the parameter value is correct.

This issue was also in Revit 2023 until the exporter update a few days ago.

[Project1_Datatype Power.zip](https://github.com/Autodesk/revit-ifc/files/11632104/Project1_Datatype.Power.zip)

### Revit Version

2022.1.x

### IFC for Revit Addon Version

22.6.2

### Windows Version

10 22H2

**Comment by AngelVelezSosa** [comment]
@WillemdBr : @EPKoele suggests that this was fixed in 2023 with the latest update, do you disagree?  If so, can you give a simple Revit and IFC file that shows the issues?

**Comment by WillemdBr** [comment]
@AngelVelezSosa We are going to look into that, maybe we used an older update version. 
In the meantime: Issue still persists in Revit 2022, Will that be fixed in the next IFC Exporter update?

**Comment by AngelVelezSosa** [comment]
If it was fixed in Revit 2023 there is a good chance it can be fixed in Revit 2022.  At the moment, we are working on Revit 2023 regressions before we work on a Revit 2022 update.

**Comment by AngelVelezSosa** [comment]
What is the unit in the IFC file?  Is it a bug (wrong value for the unit in the IFC file) or just that we don't support VA (which would be an improvement)?

**Comment by WillemdBr** [comment]
I think it is IFCPOWERMEASURE? not sure how to read unit types but opening the IFC in Notepad++ gave me this result:
![image](https://github.com/Autodesk/revit-ifc/assets/32219489/461a3371-f8b4-4665-83ba-4da580604cf5)

**Comment by AngelVelezSosa** [comment]
OK, we will look at that.  That should have already been fixed.

**Comment by AngelVelezSosa** [comment]
It does look like that is 23.2.3, and the latest version is 23.3.  Let me check the release notes.

**Comment by AngelVelezSosa** [comment]
That does look fixed for me, so probably fixed in 23.3 and scheduled for a 2022 update.

**Comment by ArtemHnatko** [comment]
The issue could not be reproduced in Revit 2023, 2024, or 2025.
Exporting the provided model to IFC 2x3 using the latest available exporter results in correct Power parameter values when using the Power data type. The previously reported invalid value behavior appears to be resolved.
**Testing environment:**
- Autodesk Revit 2023 (IFC 23.4.1.0)
- Autodesk Revit 2024 (IFC 24.3.20.0)
- Autodesk Revit 2025 (IFC 25.4.0.27)

![Image](https://github.com/user-attachments/assets/eceb840b-2663-4849-9c02-46d6b0a2ca12)
